# Generated by Django 6.0.7 on 2026-07-26 16:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(84)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
